// AUTO-GENERATED by scripts/genCashbookIcons.mjs — do not edit by hand.
// Regenerate with: node scripts/genCashbookIcons.mjs
import type { IconNode } from "lucide-react-native";

export const CASHBOOK_ICON_NODES: Record<string, IconNode> = {
    "wallet": [
        [
            "path",
            {
                "d": "M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1",
                "key": "18etb6"
            }
        ],
        [
            "path",
            {
                "d": "M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4",
                "key": "xoc0q4"
            }
        ]
    ],
    "shopping-cart": [
        [
            "circle",
            {
                "cx": "8",
                "cy": "21",
                "r": "1",
                "key": "jimo8o"
            }
        ],
        [
            "circle",
            {
                "cx": "19",
                "cy": "21",
                "r": "1",
                "key": "13723u"
            }
        ],
        [
            "path",
            {
                "d": "M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12",
                "key": "9zh506"
            }
        ]
    ],
    "house": [
        [
            "path",
            {
                "d": "M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8",
                "key": "5wwlr5"
            }
        ],
        [
            "path",
            {
                "d": "M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z",
                "key": "r6nss1"
            }
        ]
    ],
    "briefcase": [
        [
            "path",
            {
                "d": "M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16",
                "key": "jecpp"
            }
        ],
        [
            "rect",
            {
                "width": "20",
                "height": "14",
                "x": "2",
                "y": "6",
                "rx": "2",
                "key": "i6l2r4"
            }
        ]
    ],
    "car": [
        [
            "path",
            {
                "d": "M19 17h2c.6 0 1-.4 1-1v-3c0-.9-.7-1.7-1.5-1.9C18.7 10.6 16 10 16 10s-1.3-1.4-2.2-2.3c-.5-.4-1.1-.7-1.8-.7H5c-.6 0-1.1.4-1.4.9l-1.4 2.9A3.7 3.7 0 0 0 2 12v4c0 .6.4 1 1 1h2",
                "key": "5owen"
            }
        ],
        [
            "circle",
            {
                "cx": "7",
                "cy": "17",
                "r": "2",
                "key": "u2ysq9"
            }
        ],
        [
            "path",
            {
                "d": "M9 17h6",
                "key": "r8uit2"
            }
        ],
        [
            "circle",
            {
                "cx": "17",
                "cy": "17",
                "r": "2",
                "key": "axvx0g"
            }
        ]
    ],
    "utensils": [
        [
            "path",
            {
                "d": "M3 2v7c0 1.1.9 2 2 2h4a2 2 0 0 0 2-2V2",
                "key": "cjf0a3"
            }
        ],
        [
            "path",
            {
                "d": "M7 2v20",
                "key": "1473qp"
            }
        ],
        [
            "path",
            {
                "d": "M21 15V2a5 5 0 0 0-5 5v6c0 1.1.9 2 2 2h3Zm0 0v7",
                "key": "j28e5"
            }
        ]
    ],
    "plane": [
        [
            "path",
            {
                "d": "M17.8 19.2 16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z",
                "key": "1v9wt8"
            }
        ]
    ],
    "heart": [
        [
            "path",
            {
                "d": "M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5",
                "key": "mvr1a0"
            }
        ]
    ],
    "gift": [
        [
            "rect",
            {
                "x": "3",
                "y": "8",
                "width": "18",
                "height": "4",
                "rx": "1",
                "key": "bkv52"
            }
        ],
        [
            "path",
            {
                "d": "M12 8v13",
                "key": "1c76mn"
            }
        ],
        [
            "path",
            {
                "d": "M19 12v7a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-7",
                "key": "6wjy6b"
            }
        ],
        [
            "path",
            {
                "d": "M7.5 8a2.5 2.5 0 0 1 0-5A4.8 8 0 0 1 12 8a4.8 8 0 0 1 4.5-5 2.5 2.5 0 0 1 0 5",
                "key": "1ihvrl"
            }
        ]
    ],
    "graduation-cap": [
        [
            "path",
            {
                "d": "M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z",
                "key": "j76jl0"
            }
        ],
        [
            "path",
            {
                "d": "M22 10v6",
                "key": "1lu8f3"
            }
        ],
        [
            "path",
            {
                "d": "M6 12.5V16a6 3 0 0 0 12 0v-3.5",
                "key": "1r8lef"
            }
        ]
    ],
    "piggy-bank": [
        [
            "path",
            {
                "d": "M11 17h3v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-3a3.16 3.16 0 0 0 2-2h1a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1h-1a5 5 0 0 0-2-4V3a4 4 0 0 0-3.2 1.6l-.3.4H11a6 6 0 0 0-6 6v1a5 5 0 0 0 2 4v3a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1z",
                "key": "1piglc"
            }
        ],
        [
            "path",
            {
                "d": "M16 10h.01",
                "key": "1m94wz"
            }
        ],
        [
            "path",
            {
                "d": "M2 8v1a2 2 0 0 0 2 2h1",
                "key": "1env43"
            }
        ]
    ],
    "building-2": [
        [
            "path",
            {
                "d": "M10 12h4",
                "key": "a56b0p"
            }
        ],
        [
            "path",
            {
                "d": "M10 8h4",
                "key": "1sr2af"
            }
        ],
        [
            "path",
            {
                "d": "M14 21v-3a2 2 0 0 0-4 0v3",
                "key": "1rgiei"
            }
        ],
        [
            "path",
            {
                "d": "M6 10H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-2",
                "key": "secmi2"
            }
        ],
        [
            "path",
            {
                "d": "M6 21V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v16",
                "key": "16ra0t"
            }
        ]
    ],
    "smartphone": [
        [
            "rect",
            {
                "width": "14",
                "height": "20",
                "x": "5",
                "y": "2",
                "rx": "2",
                "ry": "2",
                "key": "1yt0o3"
            }
        ],
        [
            "path",
            {
                "d": "M12 18h.01",
                "key": "mhygvu"
            }
        ]
    ],
    "dumbbell": [
        [
            "path",
            {
                "d": "M17.596 12.768a2 2 0 1 0 2.829-2.829l-1.768-1.767a2 2 0 0 0 2.828-2.829l-2.828-2.828a2 2 0 0 0-2.829 2.828l-1.767-1.768a2 2 0 1 0-2.829 2.829z",
                "key": "9m4mmf"
            }
        ],
        [
            "path",
            {
                "d": "m2.5 21.5 1.4-1.4",
                "key": "17g3f0"
            }
        ],
        [
            "path",
            {
                "d": "m20.1 3.9 1.4-1.4",
                "key": "1qn309"
            }
        ],
        [
            "path",
            {
                "d": "M5.343 21.485a2 2 0 1 0 2.829-2.828l1.767 1.768a2 2 0 1 0 2.829-2.829l-6.364-6.364a2 2 0 1 0-2.829 2.829l1.768 1.767a2 2 0 0 0-2.828 2.829z",
                "key": "1t2c92"
            }
        ],
        [
            "path",
            {
                "d": "m9.6 14.4 4.8-4.8",
                "key": "6umqxw"
            }
        ]
    ]
} as unknown as Record<string, IconNode>;

export const CASHBOOK_ICON_KEYS: string[] = Object.keys(CASHBOOK_ICON_NODES);
