import { StyleSheet } from "react-native";

export const createDashboardStyles = (theme: any) =>
    StyleSheet.create({
        container: { flex: 1, backgroundColor: theme.colors.background },
        headerDecoration: {
            position: "absolute",
            top: 0,
            left: 0,
            right: 0,
            backgroundColor: theme.colors.incomeBg,
            borderBottomLeftRadius: 40,
            borderBottomRightRadius: 40,
            opacity: 0.6,
        },

        // Modern Header
        modernHeader: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            paddingHorizontal: 20,
            paddingBottom: 20,
        },
        greetingText: {
            fontSize: 13,
            fontWeight: "600",
            color: theme.colors.primary,
            textTransform: "uppercase",
            letterSpacing: 0.5,
        },
        userNameText: { fontSize: 26, fontWeight: "bold", color: theme.colors.text, marginTop: 2 },
        notificationBtn: {
            width: 48,
            height: 48,
            borderRadius: 24,
            backgroundColor: theme.colors.card,
            alignItems: "center",
            justifyContent: "center",
            elevation: 3,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.08,
            shadowRadius: 4,
        },

        // Hero Section
        heroSection: { paddingHorizontal: 20, marginTop: 10, marginBottom: 10 },
        heroCard: {
            backgroundColor: theme.colors.primary,
            borderRadius: 32,
            padding: 24,
            elevation: 8,
            shadowColor: theme.colors.primary,
            shadowOffset: { width: 0, height: 10 },
            shadowOpacity: 0.2,
            shadowRadius: 15,
        },
        heroTitle: {
            fontSize: 30,
            fontWeight: "bold",
            color: "white",
            lineHeight: 38,
            marginBottom: 12,
        },
        heroSubtitle: {
            fontSize: 14,
            color: "rgba(255,255,255,0.8)",
            lineHeight: 22,
            maxWidth: "85%",
        },
        heroBadge: {
            position: "absolute",
            right: 20,
            top: 20,
            paddingHorizontal: 10,
            paddingVertical: 4,
            borderRadius: 20,
            backgroundColor: "rgba(255,255,255,0.2)",
        },
        heroBadgeText: { fontSize: 10, color: "white", fontWeight: "bold" },

        // Balance Card
        modernBalanceCard: {
            backgroundColor: theme.colors.darkCard,
            marginHorizontal: 20,
            borderRadius: 24,
            padding: 24,
            height: 180,
            justifyContent: "space-between",
            elevation: 8,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.3,
            shadowRadius: 10,
            marginTop: 10,
        },
        balanceHeader: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
        },
        balanceTitle: { fontSize: 32, fontWeight: "bold", color: "white" },
        balanceSubtitle: { fontSize: 14, color: "rgba(255,255,255,0.6)", marginTop: -15 },
        cardFooter: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
        cardNumber: { fontSize: 16, color: "rgba(255,255,255,0.8)", letterSpacing: 0.5 },
        mastercardLogo: { flexDirection: "row" },
        circle: { width: 20, height: 20, borderRadius: 10, opacity: 0.8 },

        // Stats Container
        statsContainer: { flexDirection: "row", paddingHorizontal: 20, gap: 16, marginTop: 20 },
        statCardFixed: { flex: 1, padding: 16, borderRadius: 20, elevation: 1 },
        statIconContainer: {
            width: 36,
            height: 36,
            borderRadius: 12,
            alignItems: "center",
            justifyContent: "center",
            marginBottom: 12,
        },
        statLabel: { fontSize: 13, color: theme.colors.textSecondary, marginBottom: 2 },
        statValue: { fontSize: 17, fontWeight: "bold", color: theme.colors.text },

        // Section Header
        sectionHeader: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            paddingHorizontal: 20,
            marginTop: 32,
            marginBottom: 16,
        },
        sectionTitle: { fontSize: 18, fontWeight: "bold", color: theme.colors.text },
        viewAllText: { fontSize: 13, color: theme.colors.textSecondary },

        // Cashbooks List
        cashbooksListModern: { paddingHorizontal: 20, paddingBottom: 40 },
        modernCashbookItem: {
            backgroundColor: theme.colors.card,
            padding: 16,
            borderRadius: 16,
            flexDirection: "row",
            alignItems: "center",
            marginBottom: 12,
            elevation: 1,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.05,
            shadowRadius: 2,
        },
        cashbookIconModern: {
            width: 44,
            height: 44,
            borderRadius: 12,
            backgroundColor: theme.colors.surface,
            alignItems: "center",
            justifyContent: "center",
        },
        cashbookInfoModern: { flex: 1, marginLeft: 16 },
        cashbookNameModern: { fontSize: 16, fontWeight: "600", color: theme.colors.text },
        cashbookMetaModern: { fontSize: 12, color: theme.colors.textSecondary },
        cashbookBalanceModern: { fontSize: 16, fontWeight: "bold" },
        balanceContainerModern: { alignItems: "flex-end", justifyContent: "center" },

        // Detail View
        detailHeader: {
            flexDirection: "row",
            alignItems: "center",
            paddingHorizontal: 20,
            paddingTop: 50,
            paddingBottom: 15,
            gap: 10,
        },
        detailBackBtn: { padding: 4 },
        detailTitle: { fontSize: 20, fontWeight: "bold", color: theme.colors.text },
        detailHeaderBtn: { padding: 4 },
        detailSearchContainer: {
            flexDirection: "row",
            alignItems: "center",
            backgroundColor: theme.colors.card,
            marginHorizontal: 20,
            paddingHorizontal: 12,
            height: 44,
            borderRadius: 12,
            borderWidth: 1,
            borderColor: theme.colors.borderLight,
            marginTop: 20,
            marginBottom: 10,
        },
        detailSearchInput: { flex: 1, marginLeft: 8, fontSize: 14, color: theme.colors.text },
        filterBar: {
            flexDirection: "row",
            alignItems: "center",
            paddingHorizontal: 20,
            marginBottom: 16,
            gap: 12,
        },
        filterRangeScroll: { flex: 1 },
        filterChip: {
            paddingHorizontal: 16,
            paddingVertical: 8,
            borderRadius: 20,
            marginRight: 8,
            borderWidth: 1,
        },
        filterChipText: {
            fontSize: 12,
            fontWeight: "600",
            textTransform: "uppercase",
        },
        exportBtn: {
            padding: 10,
            borderRadius: 12,
            backgroundColor: theme.colors.card,
            borderWidth: 1,
            borderColor: theme.colors.borderLight,
            elevation: 2,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
        },
        detailList: { paddingHorizontal: 20, marginTop: 10 },
        listLabel: { fontSize: 16, fontWeight: "bold", color: theme.colors.text, marginBottom: 16 },
        modernTxItem: { flexDirection: "row", alignItems: "center", marginBottom: 20 },
        txIconContainer: {
            width: 48,
            height: 48,
            borderRadius: 12,
            alignItems: "center",
            justifyContent: "center",
        },
        txInfo: { flex: 1, marginLeft: 16 },
        txTitle: { fontSize: 16, fontWeight: "600", color: theme.colors.text },
        txSubTitle: { fontSize: 12, color: theme.colors.textSecondary },
        txRight: { alignItems: "flex-end" },
        txAmountModern: { fontSize: 16, fontWeight: "bold" },

        // Bottom Actions
        modernBottomActions: {
            position: "absolute",
            bottom: 0,
            left: 0,
            right: 0,
            flexDirection: "row",
            padding: 20,
            gap: 12,
            backgroundColor: theme.colors.card,
            borderTopLeftRadius: 24,
            borderTopRightRadius: 24,
            elevation: 10,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: -4 },
            shadowOpacity: 0.1,
            shadowRadius: 8,
        },
        bigActionBtnModern: {
            flex: 1,
            height: 50,
            borderRadius: 12,
            alignItems: "center",
            justifyContent: "center",
        },
        bigActionBtnTextModern: { fontSize: 15, fontWeight: "bold" },

        // Modal Modern
        modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.4)", justifyContent: "flex-end" },
        modalContentModern: {
            backgroundColor: theme.colors.card,
            borderTopLeftRadius: 32,
            borderTopRightRadius: 32,
            padding: 24,
            paddingBottom: 40,
        },
        modalHeaderModern: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: 24,
        },
        modalTitleModern: { fontSize: 20, fontWeight: "bold", color: theme.colors.text },
        inputLabelModern: { fontSize: 13, color: theme.colors.textSecondary, marginBottom: 8 },
        modalInputLargeModern: {
            fontSize: 40,
            fontWeight: "bold",
            color: theme.colors.text,
            borderBottomWidth: 1,
            borderBottomColor: theme.colors.border,
            paddingVertical: 8,
            marginBottom: 24,
        },
        categoryPicker: { flexDirection: "row", marginBottom: 24 },
        categoryChip: {
            paddingHorizontal: 16,
            paddingVertical: 8,
            borderRadius: 12,
            backgroundColor: theme.colors.surface,
            marginRight: 8,
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        categoryChipActive: { backgroundColor: theme.colors.primary },
        categoryChipText: { fontSize: 14, color: theme.colors.textSecondary },
        categoryChipTextActive: { color: "white", fontWeight: "500" },
        modalInputModern: {
            height: 50,
            borderRadius: 12,
            borderWidth: 1,
            borderColor: theme.colors.border,
            backgroundColor: theme.colors.background,
            paddingHorizontal: 16,
            fontSize: 15,
            color: theme.colors.text,
            marginBottom: 24,
        },
        submitBtnModern: {
            height: 56,
            borderRadius: 16,
            alignItems: "center",
            justifyContent: "center",
            elevation: 4,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.2,
            shadowRadius: 4,
        },
        submitBtnTextModern: { color: "white", fontSize: 16, fontWeight: "bold" },
        emptyContainer: { padding: 40, alignItems: "center" },
        emptyIconContainer: {
            width: 80,
            height: 80,
            borderRadius: 40,
            backgroundColor: theme.colors.surface,
            alignItems: "center",
            justifyContent: "center",
            marginBottom: 16,
        },
        emptyState: { padding: 20, alignItems: "center" },
        emptyText: { color: theme.colors.textSecondary, textAlign: "center" },

        // Transaction Detail Modal
        txDetailCard: {
            backgroundColor: theme.colors.card,
            borderTopLeftRadius: 32,
            borderTopRightRadius: 32,
            padding: 24,
            paddingBottom: 60,
        },
        txDetailHeader: { alignItems: "center", marginBottom: 30 },
        txDetailTypeBadge: {
            paddingHorizontal: 16,
            paddingVertical: 6,
            borderRadius: 20,
            marginBottom: 12,
        },
        txDetailAmount: { fontSize: 40, fontWeight: "bold", color: theme.colors.text },
        txDetailDescription: { fontSize: 18, color: theme.colors.textSecondary, marginTop: 4 },
        txDetailInfoSection: {
            backgroundColor: theme.colors.surface,
            borderRadius: 20,
            padding: 20,
            gap: 20,
        },
        txDetailRow: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
        },
        txDetailLabel: { fontSize: 14, color: theme.colors.textSecondary },
        txDetailValue: { fontSize: 15, fontWeight: "600", color: theme.colors.text },
        txDetailActions: { flexDirection: "row", gap: 12, marginTop: 30 },
        txDetailDeleteBtn: {
            flex: 1,
            height: 50,
            borderRadius: 12,
            borderWidth: 1,
            borderColor: theme.colors.error,
            alignItems: "center",
            justifyContent: "center",
        },
        txDetailCloseBtn: {
            flex: 2,
            height: 50,
            borderRadius: 12,
            backgroundColor: theme.colors.primary,
            alignItems: "center",
            justifyContent: "center",
        },
    });
