import { StyleSheet } from "react-native";

export const createDashboardStyles = (theme: any) =>
    StyleSheet.create({
        container: { flex: 1, backgroundColor: theme.colors.background },
        headerDecoration: {
            position: "absolute",
            top: 0,
            left: 0,
            right: 0,
            backgroundColor: theme.colors.primaryContainer,
            borderBottomLeftRadius: 40,
            borderBottomRightRadius: 40,
            opacity: 0.5,
        },

        // Modern Header
        modernHeader: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            paddingHorizontal: 20,
            paddingBottom: 16,
        },
        greetingText: {
            fontSize: 12,
            fontWeight: "700",
            color: theme.colors.primary,
            textTransform: "uppercase",
            letterSpacing: 0.8,
        },
        userNameText: {
            fontSize: 28,
            fontWeight: "800",
            color: theme.colors.onSurface,
            marginTop: 2,
            letterSpacing: -0.3,
        },
        // Hero Section
        heroSection: { paddingHorizontal: 20, marginTop: 8, marginBottom: 8 },
        heroCard: {
            borderRadius: theme.shape.extraLarge,
            padding: 22,
            overflow: "hidden",
            ...theme.elevation.level3,
            shadowColor: theme.colors.shadow,
        },

        heroGlow: {
            position: "absolute",
            top: -80,
            left: -60,
            width: 220,
            height: 220,
            borderRadius: 110,
            backgroundColor: "rgba(255,255,255,0.12)",
        },
        heroTitle: {
            fontSize: 32,
            fontWeight: "800",
            color: "#FFFFFF",
            lineHeight: 40,
            marginBottom: 14,
        },

        heroSubtitle: {
            fontSize: 14,
            color: "rgba(255,255,255,0.85)",
            lineHeight: 22,
            maxWidth: "88%",
        },
        heroBadge: {
            position: "absolute",
            right: 20,
            top: 20,
            paddingHorizontal: 12,
            paddingVertical: 6,
            borderRadius: 999,
            backgroundColor: "rgba(255,255,255,0.2)",
        },

        heroBadgeText: {
            fontSize: 10,
            color: "#FFFFFF",
            fontWeight: "700",
            letterSpacing: 0.4,
        },

        // Balance Card
        modernBalanceCard: {
            marginHorizontal: 20,
            borderRadius: theme.shape.extraLarge,
            padding: 22,
            height: 175,
            justifyContent: "space-between",
            marginTop: 10,
            overflow: "hidden",
            ...theme.elevation.level3,
            shadowColor: theme.colors.shadow,
        },

        cardGlow: {
            position: "absolute",
            top: -60,
            right: -80,
            width: 220,
            height: 220,
            borderRadius: 110,
            backgroundColor: "rgba(255,255,255,0.06)",
        },
        balanceHeader: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
        },
        balanceTitle: {
            fontSize: 30,
            fontWeight: "800",
            color: "#FFFFFF",
            letterSpacing: -0.5,
        },
        balanceSubtitle: {
            fontSize: 13,
            color: "rgba(255,255,255,0.6)",
            marginTop: -12,
            fontWeight: "500",
        },
        cardFooter: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
        cardNumber: { fontSize: 14, color: "rgba(255,255,255,0.7)", letterSpacing: 0.5, fontWeight: "500" },
        mastercardLogo: { flexDirection: "row" },
        circle: { width: 20, height: 20, borderRadius: 10, opacity: 0.8 },

        // Stats Container
        statsContainer: {
            flexDirection: "row",
            paddingHorizontal: 20,
            gap: 12,
            marginTop: 16,
        },
        statCardFixed: {
            flex: 1,
            padding: 16,
            borderRadius: theme.shape.largeIncreased,
            backgroundColor: theme.colors.surfaceContainerLow,
            ...theme.elevation.level1,
            shadowColor: theme.colors.shadow,
        },
        statIconContainer: {
            width: 38,
            height: 38,
            borderRadius: 12,
            alignItems: "center",
            justifyContent: "center",
            marginBottom: 12,
        },
        statLabel: {
            fontSize: 12,
            color: theme.colors.onSurfaceVariant,
            marginBottom: 2,
            fontWeight: "500",
        },
        statValue: {
            fontSize: 18,
            fontWeight: "700",
            color: theme.colors.onSurface,
            letterSpacing: -0.3,
        },

        // Section Header
        sectionHeader: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            paddingHorizontal: 20,
            marginTop: 28,
            marginBottom: 14,
        },
        sectionTitle: {
            fontSize: 17,
            fontWeight: "700",
            color: theme.colors.onSurface,
            letterSpacing: -0.2,
        },
        viewAllText: {
            fontSize: 12,
            color: theme.colors.primary,
            fontWeight: "600",
        },

        // Cashbooks List
        cashbooksListModern: { paddingHorizontal: 20, paddingBottom: 40 },
        modernCashbookItem: {
            backgroundColor: theme.colors.surfaceContainerLow,
            padding: 14,
            borderRadius: theme.shape.largeIncreased,
            flexDirection: "row",
            alignItems: "center",
            marginBottom: 12,
            ...theme.elevation.level1,
            shadowColor: theme.colors.shadow,
        },
        cashbookIconModern: {
            width: 46,
            height: 46,
            borderRadius: 23,
            backgroundColor: theme.colors.secondaryContainer,
            alignItems: "center",
            justifyContent: "center",
        },
        cashbookInfoModern: { flex: 1, marginLeft: 14 },
        cashbookNameModern: {
            fontSize: 15,
            fontWeight: "600",
            color: theme.colors.onSurface,
            letterSpacing: -0.1,
        },
        cashbookMetaModern: {
            fontSize: 12,
            color: theme.colors.onSurfaceVariant,
            marginTop: 2,
        },
        cashbookBalanceModern: {
            fontSize: 15,
            fontWeight: "700",
            letterSpacing: -0.2,
        },
        balanceContainerModern: { alignItems: "flex-end", justifyContent: "center" },

        // Detail View
        detailHeader: {
            flexDirection: "row",
            alignItems: "center",
            paddingHorizontal: 20,
            paddingTop: 50,
            paddingBottom: 15,
            gap: 10,
        },
        detailBackBtn: { padding: 4 },
        detailTitle: {
            fontSize: 22,
            fontWeight: "700",
            color: theme.colors.onSurface,
            letterSpacing: -0.2,
        },
        detailHeaderBtn: { padding: 4 },
        detailSearchContainer: {
            flexDirection: "row",
            alignItems: "center",
            backgroundColor: theme.colors.surfaceContainerHighest,
            marginHorizontal: 20,
            paddingHorizontal: 14,
            height: 48,
            borderRadius: theme.shape.medium,
            marginTop: 16,
            marginBottom: 10,
        },
        detailSearchInput: { flex: 1, marginLeft: 8, fontSize: 14, color: theme.colors.onSurface },
        filterBar: {
            flexDirection: "row",
            alignItems: "center",
            paddingHorizontal: 20,
            marginBottom: 12,
            gap: 10,
        },
        filterRangeScroll: { flex: 1 },
        filterChip: {
            paddingHorizontal: 14,
            paddingVertical: 8,
            borderRadius: theme.shape.small,
            marginRight: 8,
            borderWidth: 1,
        },
        filterChipText: {
            fontSize: 11,
            fontWeight: "600",
            textTransform: "uppercase",
            letterSpacing: 0.3,
        },
        exportBtn: {
            padding: 11,
            borderRadius: theme.shape.medium,
            backgroundColor: theme.colors.surfaceContainerHighest,
        },
        detailList: { paddingHorizontal: 20, marginTop: 8 },
        listLabel: {
            fontSize: 15,
            fontWeight: "700",
            color: theme.colors.onSurface,
            marginBottom: 14,
            letterSpacing: -0.1,
        },
        modernTxItem: {
            flexDirection: "row",
            alignItems: "center",
            marginBottom: 16,
        },
        txIconContainer: {
            width: 44,
            height: 44,
            borderRadius: 22,
            alignItems: "center",
            justifyContent: "center",
        },
        txInfo: { flex: 1, marginLeft: 14 },
        txTitle: {
            fontSize: 14,
            fontWeight: "600",
            color: theme.colors.onSurface,
        },
        txSubTitle: {
            fontSize: 11,
            color: theme.colors.onSurfaceVariant,
            marginTop: 2,
        },
        txRight: { alignItems: "flex-end" },
        txAmountModern: {
            fontSize: 15,
            fontWeight: "700",
            letterSpacing: -0.2,
        },

        // Bottom Actions
        modernBottomActions: {
            position: "absolute",
            bottom: 0,
            left: 0,
            right: 0,
            flexDirection: "row",
            padding: 16,
            paddingHorizontal: 20,
            gap: 12,
            backgroundColor: theme.colors.surfaceContainer,
            borderTopLeftRadius: theme.shape.extraLarge,
            borderTopRightRadius: theme.shape.extraLarge,
            borderBottomLeftRadius: theme.shape.extraLarge,
            borderBottomRightRadius: theme.shape.extraLarge,
            marginHorizontal: 12,
            ...theme.elevation.level2,
            shadowColor: theme.colors.shadow,
        },
        bigActionBtnModern: {
            flex: 1,
            height: 52,
            borderRadius: theme.shape.full,
            alignItems: "center",
            justifyContent: "center",
        },
        bigActionBtnTextModern: {
            fontSize: 14,
            fontWeight: "700",
            letterSpacing: 0.5,
        },

        inputLabelModern: {
            fontSize: 12,
            color: theme.colors.onSurfaceVariant,
            marginBottom: 8,
            fontWeight: "600",
            textTransform: "uppercase",
            letterSpacing: 0.5,
        },
        modalInputLargeModern: {
            fontSize: 38,
            fontWeight: "800",
            color: theme.colors.onSurface,
            borderBottomWidth: 2,
            borderBottomColor: theme.colors.outline,
            paddingVertical: 8,
            marginBottom: 24,
        },
        categoryPicker: { flexDirection: "row", marginBottom: 24 },
        categoryChip: {
            paddingHorizontal: 14,
            paddingVertical: 8,
            borderRadius: theme.shape.small,
            backgroundColor: "transparent",
            marginRight: 8,
            borderWidth: 1,
            borderColor: theme.colors.outlineVariant,
        },
        categoryChipActive: {
            backgroundColor: theme.colors.secondaryContainer,
            borderColor: theme.colors.secondaryContainer,
        },
        categoryChipText: { fontSize: 13, color: theme.colors.onSurfaceVariant, fontWeight: "500" },
        categoryChipTextActive: { color: theme.colors.onSecondaryContainer, fontWeight: "600" },
        modalInputModern: {
            height: 52,
            borderRadius: theme.shape.medium,
            borderWidth: 1,
            borderColor: theme.colors.outline,
            backgroundColor: theme.colors.surfaceContainerHighest,
            paddingHorizontal: 16,
            fontSize: 14,
            color: theme.colors.onSurface,
            marginBottom: 24,
        },
        submitBtnModern: {
            height: 56,
            borderRadius: theme.shape.full,
            alignItems: "center",
            justifyContent: "center",
            ...theme.elevation.level1,
            shadowColor: theme.colors.shadow,
        },
        submitBtnTextModern: {
            color: theme.colors.onPrimary,
            fontSize: 15,
            fontWeight: "700",
            letterSpacing: 0.3,
        },
        emptyContainer: { padding: 40, alignItems: "center" },
        emptyIconContainer: {
            width: 80,
            height: 80,
            borderRadius: 40,
            backgroundColor: theme.colors.secondaryContainer,
            alignItems: "center",
            justifyContent: "center",
            marginBottom: 16,
        },
        emptyState: { padding: 20, alignItems: "center" },
        emptyText: {
            color: theme.colors.onSurfaceVariant,
            textAlign: "center",
            fontSize: 14,
            lineHeight: 20,
        },

        // Transaction Detail Modal
        txDetailCard: {
            backgroundColor: theme.colors.surfaceContainerLow,
            borderTopLeftRadius: theme.shape.extraLarge,
            borderTopRightRadius: theme.shape.extraLarge,
            padding: 24,
            paddingBottom: 60,
        },
        txDetailHeader: { alignItems: "center", marginBottom: 28 },
        txDetailTypeBadge: {
            paddingHorizontal: 14,
            paddingVertical: 6,
            borderRadius: 999,
            marginBottom: 12,
        },
        txDetailAmount: {
            fontSize: 36,
            fontWeight: "800",
            color: theme.colors.onSurface,
            letterSpacing: -0.5,
        },
        txDetailDescription: {
            fontSize: 16,
            color: theme.colors.onSurfaceVariant,
            marginTop: 4,
            fontWeight: "500",
        },
        txDetailInfoSection: {
            backgroundColor: theme.colors.surfaceContainerHigh,
            borderRadius: theme.shape.large,
            padding: 18,
            gap: 18,
        },
        txDetailRow: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
        },
        txDetailLabel: {
            fontSize: 13,
            color: theme.colors.onSurfaceVariant,
            fontWeight: "500",
        },
        txDetailValue: {
            fontSize: 14,
            fontWeight: "600",
            color: theme.colors.onSurface,
        },
        txDetailActions: { flexDirection: "row", gap: 10, marginTop: 28 },
        txDetailDeleteBtn: {
            flex: 1,
            height: 52,
            borderRadius: theme.shape.full,
            borderWidth: 1,
            borderColor: theme.colors.error,
            alignItems: "center",
            justifyContent: "center",
        },
        txDetailCloseBtn: {
            flex: 2,
            height: 52,
            borderRadius: theme.shape.full,
            backgroundColor: theme.colors.primary,
            alignItems: "center",
            justifyContent: "center",
        },
    });
