import { StyleSheet } from "react-native";

export const createDashboardStyles = (theme: any) =>
    StyleSheet.create({
        container: { flex: 1, backgroundColor: theme.colors.background },
        headerDecoration: {
            position: "absolute",
            top: 0,
            left: 0,
            right: 0,
            backgroundColor: theme.colors.incomeBg,
            borderBottomLeftRadius: 40,
            borderBottomRightRadius: 40,
            opacity: 0.6,
        },

        // Modern Header
        modernHeader: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            paddingHorizontal: 20,
            paddingBottom: 16,
        },
        greetingText: {
            fontSize: 12,
            fontWeight: "700",
            color: theme.colors.primary,
            textTransform: "uppercase",
            letterSpacing: 0.8,
        },
        userNameText: {
            fontSize: 26,
            fontWeight: "800",
            color: theme.colors.text,
            marginTop: 2,
            letterSpacing: -0.3,
        },
        // Hero Section
        heroSection: { paddingHorizontal: 20, marginTop: 8, marginBottom: 8 },
        heroCard: {
            borderRadius: 20,
            padding: 22,
            elevation: 4,
            shadowColor: "#1A1A17",
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.1,
            shadowRadius: 16,
            overflow: "hidden",
        },

        heroGlow: {
            position: "absolute",
            top: -80,
            left: -60,
            width: 220,
            height: 220,
            borderRadius: 110,
            backgroundColor: "rgba(255,255,255,0.12)",
        },
        heroTitle: {
            fontSize: 32,
            fontWeight: "800",
            color: "white",
            lineHeight: 40,
            marginBottom: 14,
        },

        heroSubtitle: {
            fontSize: 14,
            color: "rgba(255,255,255,0.85)",
            lineHeight: 22,
            maxWidth: "88%",
        },
        heroBadge: {
            position: "absolute",
            right: 20,
            top: 20,
            paddingHorizontal: 12,
            paddingVertical: 6,
            borderRadius: 999,
            backgroundColor: "rgba(255,255,255,0.2)",
        },

        heroBadgeText: {
            fontSize: 10,
            color: "white",
            fontWeight: "700",
            letterSpacing: 0.4,
        },

        // Balance Card
        modernBalanceCard: {
            marginHorizontal: 20,
            borderRadius: 20,
            padding: 22,
            height: 175,
            justifyContent: "space-between",
            elevation: 4,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 3 },
            shadowOpacity: 0.12,
            shadowRadius: 12,
            marginTop: 10,
            overflow: "hidden",
        },

        cardGlow: {
            position: "absolute",
            top: -60,
            right: -80,
            width: 220,
            height: 220,
            borderRadius: 110,
            backgroundColor: "rgba(255,255,255,0.06)",
        },
        balanceHeader: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
        },
        balanceTitle: {
            fontSize: 30,
            fontWeight: "800",
            color: "white",
            letterSpacing: -0.5,
        },
        balanceSubtitle: {
            fontSize: 13,
            color: "rgba(255,255,255,0.6)",
            marginTop: -12,
            fontWeight: "500",
        },
        cardFooter: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
        cardNumber: { fontSize: 14, color: "rgba(255,255,255,0.7)", letterSpacing: 0.5, fontWeight: "500" },
        mastercardLogo: { flexDirection: "row" },
        circle: { width: 20, height: 20, borderRadius: 10, opacity: 0.8 },

        // Stats Container
        statsContainer: {
            flexDirection: "row",
            paddingHorizontal: 20,
            gap: 12,
            marginTop: 16,
        },
        statCardFixed: {
            flex: 1,
            padding: 14,
            borderRadius: 16,
            elevation: 1,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.02,
            shadowRadius: 3,
        },
        statIconContainer: {
            width: 34,
            height: 34,
            borderRadius: 10,
            alignItems: "center",
            justifyContent: "center",
            marginBottom: 10,
        },
        statLabel: {
            fontSize: 12,
            color: theme.colors.textSecondary,
            marginBottom: 2,
            fontWeight: "500",
        },
        statValue: {
            fontSize: 16,
            fontWeight: "700",
            color: theme.colors.text,
            letterSpacing: -0.3,
        },

        // Section Header
        sectionHeader: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            paddingHorizontal: 20,
            marginTop: 28,
            marginBottom: 14,
        },
        sectionTitle: {
            fontSize: 17,
            fontWeight: "700",
            color: theme.colors.text,
            letterSpacing: -0.2,
        },
        viewAllText: {
            fontSize: 12,
            color: theme.colors.textSecondary,
            fontWeight: "500",
        },

        // Cashbooks List
        cashbooksListModern: { paddingHorizontal: 20, paddingBottom: 40 },
        modernCashbookItem: {
            backgroundColor: theme.colors.card,
            padding: 14,
            borderRadius: 14,
            flexDirection: "row",
            alignItems: "center",
            marginBottom: 10,
            elevation: 1,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.02,
            shadowRadius: 3,
        },
        cashbookIconModern: {
            width: 42,
            height: 42,
            borderRadius: 12,
            backgroundColor: theme.colors.surface,
            alignItems: "center",
            justifyContent: "center",
        },
        cashbookInfoModern: { flex: 1, marginLeft: 14 },
        cashbookNameModern: {
            fontSize: 15,
            fontWeight: "600",
            color: theme.colors.text,
            letterSpacing: -0.1,
        },
        cashbookMetaModern: {
            fontSize: 12,
            color: theme.colors.textSecondary,
            marginTop: 2,
        },
        cashbookBalanceModern: {
            fontSize: 15,
            fontWeight: "700",
            letterSpacing: -0.2,
        },
        balanceContainerModern: { alignItems: "flex-end", justifyContent: "center" },

        // Detail View
        detailHeader: {
            flexDirection: "row",
            alignItems: "center",
            paddingHorizontal: 20,
            paddingTop: 50,
            paddingBottom: 15,
            gap: 10,
        },
        detailBackBtn: { padding: 4 },
        detailTitle: {
            fontSize: 20,
            fontWeight: "700",
            color: theme.colors.text,
            letterSpacing: -0.2,
        },
        detailHeaderBtn: { padding: 4 },
        detailSearchContainer: {
            flexDirection: "row",
            alignItems: "center",
            backgroundColor: theme.colors.card,
            marginHorizontal: 20,
            paddingHorizontal: 12,
            height: 42,
            borderRadius: 12,
            borderWidth: 1,
            borderColor: theme.colors.borderLight,
            marginTop: 16,
            marginBottom: 10,
        },
        detailSearchInput: { flex: 1, marginLeft: 8, fontSize: 14, color: theme.colors.text },
        filterBar: {
            flexDirection: "row",
            alignItems: "center",
            paddingHorizontal: 20,
            marginBottom: 12,
            gap: 10,
        },
        filterRangeScroll: { flex: 1 },
        filterChip: {
            paddingHorizontal: 14,
            paddingVertical: 7,
            borderRadius: 20,
            marginRight: 8,
            borderWidth: 1,
        },
        filterChipText: {
            fontSize: 11,
            fontWeight: "600",
            textTransform: "uppercase",
            letterSpacing: 0.3,
        },
        exportBtn: {
            padding: 9,
            borderRadius: 10,
            backgroundColor: theme.colors.card,
            borderWidth: 1,
            borderColor: theme.colors.borderLight,
            elevation: 1,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.06,
            shadowRadius: 3,
        },
        detailList: { paddingHorizontal: 20, marginTop: 8 },
        listLabel: {
            fontSize: 15,
            fontWeight: "700",
            color: theme.colors.text,
            marginBottom: 14,
            letterSpacing: -0.1,
        },
        modernTxItem: {
            flexDirection: "row",
            alignItems: "center",
            marginBottom: 16,
        },
        txIconContainer: {
            width: 44,
            height: 44,
            borderRadius: 12,
            alignItems: "center",
            justifyContent: "center",
        },
        txInfo: { flex: 1, marginLeft: 14 },
        txTitle: {
            fontSize: 14,
            fontWeight: "600",
            color: theme.colors.text,
        },
        txSubTitle: {
            fontSize: 11,
            color: theme.colors.textSecondary,
            marginTop: 2,
        },
        txRight: { alignItems: "flex-end" },
        txAmountModern: {
            fontSize: 15,
            fontWeight: "700",
            letterSpacing: -0.2,
        },

        // Bottom Actions
        modernBottomActions: {
            position: "absolute",
            bottom: 86,
            left: 0,
            right: 0,
            flexDirection: "row",
            padding: 16,
            paddingHorizontal: 20,
            gap: 12,
            backgroundColor: theme.colors.card,
            borderTopLeftRadius: 20,
            borderTopRightRadius: 20,
            borderBottomLeftRadius: 20,
            borderBottomRightRadius: 20,
            marginHorizontal: 12,
            elevation: 4,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: -2 },
            shadowOpacity: 0.04,
            shadowRadius: 8,
        },
        bigActionBtnModern: {
            flex: 1,
            height: 48,
            borderRadius: 12,
            alignItems: "center",
            justifyContent: "center",
        },
        bigActionBtnTextModern: {
            fontSize: 14,
            fontWeight: "700",
            letterSpacing: 0.5,
        },

        // Modal Modern
        modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.45)", justifyContent: "flex-end" },
        modalContentModern: {
            backgroundColor: theme.colors.card,
            borderTopLeftRadius: 28,
            borderTopRightRadius: 28,
            padding: 24,
            paddingBottom: 40,
        },
        modalHeaderModern: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: 24,
        },
        modalTitleModern: {
            fontSize: 20,
            fontWeight: "700",
            color: theme.colors.text,
            letterSpacing: -0.2,
        },
        inputLabelModern: {
            fontSize: 12,
            color: theme.colors.textSecondary,
            marginBottom: 8,
            fontWeight: "600",
            textTransform: "uppercase",
            letterSpacing: 0.5,
        },
        modalInputLargeModern: {
            fontSize: 38,
            fontWeight: "800",
            color: theme.colors.text,
            borderBottomWidth: 2,
            borderBottomColor: theme.colors.border,
            paddingVertical: 8,
            marginBottom: 24,
        },
        categoryPicker: { flexDirection: "row", marginBottom: 24 },
        categoryChip: {
            paddingHorizontal: 14,
            paddingVertical: 8,
            borderRadius: 10,
            backgroundColor: theme.colors.surface,
            marginRight: 8,
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        categoryChipActive: {
            backgroundColor: theme.colors.primary,
            borderColor: theme.colors.primary,
        },
        categoryChipText: { fontSize: 13, color: theme.colors.textSecondary, fontWeight: "500" },
        categoryChipTextActive: { color: "white", fontWeight: "600" },
        modalInputModern: {
            height: 48,
            borderRadius: 12,
            borderWidth: 1,
            borderColor: theme.colors.border,
            backgroundColor: theme.colors.background,
            paddingHorizontal: 16,
            fontSize: 14,
            color: theme.colors.text,
            marginBottom: 24,
        },
        submitBtnModern: {
            height: 52,
            borderRadius: 14,
            alignItems: "center",
            justifyContent: "center",
            elevation: 2,
            shadowColor: "#000",
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.08,
            shadowRadius: 4,
        },
        submitBtnTextModern: {
            color: "white",
            fontSize: 15,
            fontWeight: "700",
            letterSpacing: 0.3,
        },
        emptyContainer: { padding: 40, alignItems: "center" },
        emptyIconContainer: {
            width: 80,
            height: 80,
            borderRadius: 40,
            backgroundColor: theme.colors.surface,
            alignItems: "center",
            justifyContent: "center",
            marginBottom: 16,
        },
        emptyState: { padding: 20, alignItems: "center" },
        emptyText: {
            color: theme.colors.textSecondary,
            textAlign: "center",
            fontSize: 14,
            lineHeight: 20,
        },

        // Transaction Detail Modal
        txDetailCard: {
            backgroundColor: theme.colors.card,
            borderTopLeftRadius: 28,
            borderTopRightRadius: 28,
            padding: 24,
            paddingBottom: 60,
        },
        txDetailHeader: { alignItems: "center", marginBottom: 28 },
        txDetailTypeBadge: {
            paddingHorizontal: 14,
            paddingVertical: 5,
            borderRadius: 20,
            marginBottom: 12,
        },
        txDetailAmount: {
            fontSize: 36,
            fontWeight: "800",
            color: theme.colors.text,
            letterSpacing: -0.5,
        },
        txDetailDescription: {
            fontSize: 16,
            color: theme.colors.textSecondary,
            marginTop: 4,
            fontWeight: "500",
        },
        txDetailInfoSection: {
            backgroundColor: theme.colors.surface,
            borderRadius: 16,
            padding: 18,
            gap: 18,
        },
        txDetailRow: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
        },
        txDetailLabel: {
            fontSize: 13,
            color: theme.colors.textSecondary,
            fontWeight: "500",
        },
        txDetailValue: {
            fontSize: 14,
            fontWeight: "600",
            color: theme.colors.text,
        },
        txDetailActions: { flexDirection: "row", gap: 10, marginTop: 28 },
        txDetailDeleteBtn: {
            flex: 1,
            height: 48,
            borderRadius: 12,
            borderWidth: 1.5,
            borderColor: theme.colors.error,
            alignItems: "center",
            justifyContent: "center",
        },
        txDetailCloseBtn: {
            flex: 2,
            height: 48,
            borderRadius: 12,
            backgroundColor: theme.colors.primary,
            alignItems: "center",
            justifyContent: "center",
        },
    });
