// Generates src/features/cashbooks/appearance/icons.data.ts from the iconNode
// arrays that lucide-react-native already ships. This guarantees the widget SVG
// and the app's Lucide component render the exact same glyph, with no runtime
// dependency on lucide-static. Re-run after changing ICON_KEYS.
import fs from "fs";
import path from "path";

const ICON_KEYS = [
    "wallet",
    "shopping-cart",
    "house",
    "briefcase",
    "car",
    "utensils",
    "plane",
    "heart",
    "gift",
    "graduation-cap",
    "piggy-bank",
    "building-2",
    "smartphone",
    "dumbbell",
];

const ICONS_DIR = "node_modules/lucide-react-native/dist/esm/icons";

const nodes = {};
for (const key of ICON_KEYS) {
    const file = path.join(ICONS_DIR, `${key}.js`);
    const src = fs.readFileSync(file, "utf8");
    const m = src.match(/createLucideIcon\(\s*"[^"]+"\s*,\s*(\[[\s\S]*?\])\s*\)\s*;/);
    if (!m) throw new Error(`Could not extract iconNode for "${key}" from ${file}`);
    // The literal uses unquoted keys (d:, key:), so evaluate it in a sandboxed
    // Function rather than JSON.parse. Source is a trusted installed package.
    const raw = new Function(`return ${m[1]};`)();
    // Drop the React "key" prop; keep only SVG attributes.
    nodes[key] = raw.map(([tag, attrs]) => [
        tag,
        Object.fromEntries(Object.entries(attrs).filter(([k]) => k !== "key")),
    ]);
}

const out =
    `// AUTO-GENERATED by scripts/genCashbookIcons.mjs — do not edit by hand.\n` +
    `// Regenerate with: node scripts/genCashbookIcons.mjs\n` +
    `import type { IconNode } from "lucide-react-native";\n\n` +
    `export const CASHBOOK_ICON_NODES: Record<string, IconNode> = ${JSON.stringify(
        nodes,
        null,
        4,
    )} as unknown as Record<string, IconNode>;\n\n` +
    `export const CASHBOOK_ICON_KEYS: string[] = Object.keys(CASHBOOK_ICON_NODES);\n`;

const dest = "src/features/cashbooks/appearance/icons.data.ts";
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.writeFileSync(dest, out);
console.log(`Wrote ${dest} with ${ICON_KEYS.length} icons`);
